### ISSUE TITLE
Minecraft crash at launch using MyLoot

### ISSUE THREAD

**Issue by Enterenn** [spoorn/myLoot#7]
It crashed with v1.5 and 1.6 on minecraft 1.18.2

Here's the error I get : 

<details>
<summary> Expand to see crash report</summary>

```
---- Minecraft Crash Report ----
// Why did you do that?

Time: 3/6/22, 11:10 AM
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'myloot'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:452)
	at net.minecraft.client.main.Main.main(Main.java:197)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.NoSuchFieldError: SHULKER_BOX
	at org.spoorn.myloot.MyLoot.onInitialize(MyLoot.java:91)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 11 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:452)

-- Initialization --
Details:
	Modules: 
		ADVAPI32.dll:API avancées Windows 32:10.0.22000.493 (WinBuild.160101.0800):Microsoft Corporation
		COMCTL32.dll:Bibliothèque de contrôles de l’expérience utilisateur:6.10 (WinBuild.160101.0800):Microsoft Corporation
		CRYPT32.dll:Crypto API32:10.0.22000.493 (WinBuild.160101.0800):Microsoft Corporation
		CRYPTBASE.dll:Base cryptographic API DLL:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		CRYPTSP.dll:Cryptographic Service Provider API:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		DBGHELP.DLL:Windows Image Helper:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		DNSAPI.dll:DNS DLL de l’API Client:10.0.22000.493 (WinBuild.160101.0800):Microsoft Corporation
		GDI32.dll:GDI Client DLL:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		IMM32.DLL:Multi-User Windows IMM32 API Client DLL:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		IPHLPAPI.DLL:API de l’application d’assistance IP:10.0.22000.493 (WinBuild.160101.0800):Microsoft Corporation
		KERNEL32.DLL:DLL du client API BASE Windows NT:10.0.22000.493 (WinBuild.160101.0800):Microsoft Corporation
		KERNELBASE.dll:DLL du client API BASE Windows NT:10.0.22000.493 (WinBuild.160101.0800):Microsoft Corporation
		MpOav.dll:IOfficeAntiVirus Module:4.18.2201.10 (WinBuild.160101.0800):Microsoft Corporation
		NSI.dll:NSI User-mode interface DLL:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		NTASN1.dll:Microsoft ASN.1 API:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		Ole32.dll:Microsoft OLE pour Windows:10.0.22000.493 (WinBuild.160101.0800):Microsoft Corporation
		OleAut32.dll:OLEAUT32.DLL:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		PSAPI.DLL:Process Status Helper:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		Pdh.dll:DLL d’application d’assistance Windows pour les données de performance:10.0.22000.493 (WinBuild.160101.0800):Microsoft Corporation
		RPCRT4.dll:Runtime d’appel de procédure distante:10.0.22000.493 (WinBuild.160101.0800):Microsoft Corporation
		SHCORE.dll:SHCORE:10.0.22000.493 (WinBuild.160101.0800):Microsoft Corporation
		SHELL32.dll:DLL commune du shell Windows:10.0.22000.493 (WinBuild.160101.0800):Microsoft Corporation
		UMPDC.dll:User Mode Power Dependency Coordinator:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		USER32.dll:DLL client de l’API uilisateur de Windows multi-utilisateurs:10.0.22000.493 (WinBuild.160101.0800):Microsoft Corporation
		USERENV.dll:Userenv:10.0.22000.493 (WinBuild.160101.0800):Microsoft Corporation
		VCRUNTIME140.dll:Microsoft® C Runtime Library:14.29.30133.0 built by: vcwrkspc:Microsoft Corporation
		VERSION.dll:Version Checking and File Installation Libraries:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		WINHTTP.dll:Services HTTP Windows:10.0.22000.493 (WinBuild.160101.0800):Microsoft Corporation
		WINMM.dll:DLL API MCI:10.0.22000.493 (WinBuild.160101.0800):Microsoft Corporation
		WS2_32.dll:Windows Socket 2.0 32-Bit DLL:10.0.22000.493 (WinBuild.160101.0800):Microsoft Corporation
		WSOCK32.dll:Windows Socket 32-Bit DLL:10.0.22000.493 (WinBuild.160101.0800):Microsoft Corporation
		amsi.dll:Anti-Malware Scan Interface:10.0.22000.120 (WinBuild.160101.0800):Microsoft Corporation
		bcrypt.dll:Bibliothèque de primitives de chiffrement Windows:10.0.22000.493 (WinBuild.160101.0800):Microsoft Corporation
		bcryptPrimitives.dll:Windows Cryptographic Primitives Library:10.0.22000.376 (WinBuild.160101.0800):Microsoft Corporation
		clbcatq.dll:COM+ Configuration Catalog:2001.12.10941.16384 (WinBuild.160101.0800):Microsoft Corporation
		combase.dll:Microsoft COM pour Windows:10.0.22000.493 (WinBuild.160101.0800):Microsoft Corporation
		dbgcore.DLL:Windows Core Debugging Helpers:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		dhcpcsvc.DLL:Service client DHCP:10.0.22000.493 (WinBuild.160101.0800):Microsoft Corporation
		dhcpcsvc6.DLL:Client DHCPv6:10.0.22000.493 (WinBuild.160101.0800):Microsoft Corporation
		fwpuclnt.dll:API en mode utilisateur FWP/IPsec:10.0.22000.493 (WinBuild.160101.0800):Microsoft Corporation
		gdi32full.dll:GDI Client DLL:10.0.22000.469 (WinBuild.160101.0800):Microsoft Corporation
		java.dll:OpenJDK Platform binary:17.0.1.0:Microsoft
		javaw.exe:OpenJDK Platform binary:17.0.1.0:Microsoft
		jimage.dll:OpenJDK Platform binary:17.0.1.0:Microsoft
		jli.dll:OpenJDK Platform binary:17.0.1.0:Microsoft
		jna10910352185144184847.dll:JNA native library:6.1.2:Java(TM) Native Access (JNA)
		jvm.dll:OpenJDK 64-Bit server VM:17.0.1.0:Microsoft
		kernel.appcore.dll:AppModel API Host:10.0.22000.71 (WinBuild.160101.0800):Microsoft Corporation
		lwjgl.dll
		management.dll:OpenJDK Platform binary:17.0.1.0:Microsoft
		management_ext.dll:OpenJDK Platform binary:17.0.1.0:Microsoft
		msvcp140.dll:Microsoft® C Runtime Library:14.29.30133.0 built by: vcwrkspc:Microsoft Corporation
		msvcp_win.dll:Microsoft® C Runtime Library:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		msvcrt.dll:Windows NT CRT DLL:7.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		mswsock.dll:Fournisseur de service Sockets 2.0 de Microsoft Windows:10.0.22000.493 (WinBuild.160101.0800):Microsoft Corporation
		napinsp.dll:Fournisseur Shim d’affectation de noms de messagerie:10.0.22000.493 (WinBuild.160101.0800):Microsoft Corporation
		ncrypt.dll:Routeur Windows NCrypt:10.0.22000.493 (WinBuild.160101.0800):Microsoft Corporation
		net.dll:OpenJDK Platform binary:17.0.1.0:Microsoft
		nio.dll:OpenJDK Platform binary:17.0.1.0:Microsoft
		nlansp_c.dll:NLA Namespace Service Provider DLL:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		ntdll.dll:DLL Couche NT:10.0.22000.493 (WinBuild.160101.0800):Microsoft Corporation
		perfos.dll:DLL d’objets Performances système Windows:10.0.22000.493 (WinBuild.160101.0800):Microsoft Corporation
		pfclient.dll:SysMain Client:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		pnrpnsp.dll:Fournisseur d’espace de noms PNRP:10.0.22000.493 (WinBuild.160101.0800):Microsoft Corporation
		powrprof.dll:DLL d’assistance du profil d’alimentation:10.0.22000.493 (WinBuild.160101.0800):Microsoft Corporation
		profapi.dll:User Profile Basic API:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		rasadhlp.dll:Remote Access AutoDial Helper:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		rsaenh.dll:Microsoft Enhanced Cryptographic Provider:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		sechost.dll:Host for SCM/SDDL/LSA Lookup APIs:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		shlwapi.dll:Bibliothèque d’utilitaires légers du Shell:10.0.22000.493 (WinBuild.160101.0800):Microsoft Corporation
		sunmscapi.dll:OpenJDK Platform binary:17.0.1.0:Microsoft
		svml.dll:OpenJDK Platform binary:17.0.1.0:Microsoft
		ucrtbase.dll:Microsoft® C Runtime Library:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		vcruntime140_1.dll:Microsoft® C Runtime Library:14.29.30133.0 built by: vcwrkspc:Microsoft Corporation
		verify.dll:OpenJDK Platform binary:17.0.1.0:Microsoft
		win32u.dll:Win32u:10.0.22000.493 (WinBuild.160101.0800):Microsoft Corporation
		windows.storage.dll:API de stockage Microsoft WinRT:10.0.22000.493 (WinBuild.160101.0800):Microsoft Corporation
		winrnr.dll:LDAP RnR Provider DLL:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		wintypes.dll:DLL de types de base Windows:10.0.22000.493 (WinBuild.160101.0800):Microsoft Corporation
		wshbth.dll:Windows Sockets Helper DLL:10.0.22000.41 (WinBuild.160101.0800):Microsoft Corporation
		zip.dll:OpenJDK Platform binary:17.0.1.0:Microsoft
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:197)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 2351717856 bytes (2242 MiB) / 2776629248 bytes (2648 MiB) up to 8589934592 bytes (8192 MiB)
	CPUs: 12
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 3600 6-Core Processor              
	Identifier: AuthenticAMD Family 23 Model 113 Stepping 0
	Microarchitecture: Zen 2
	Frequency (GHz): 3.60
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: AMD Radeon RX 5700 XT
	Graphics card #0 vendor: Advanced Micro Devices, Inc. (0x1002)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x731f
	Graphics card #0 versionInfo: DriverVersion=30.0.14029.5006
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.40
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.40
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 23478.08
	Virtual memory used (MB): 14609.78
	Swap memory total (MB): 7168.00
	Swap memory used (MB): 48.31
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx8192m -Xms256m
	Fabric Mods: 
		additionaladditions: Additional Additions 3.0.1
		amplified-nether: Amplified Nether 1.1
		appleskin: AppleSkin 2.3.0+mc1.18.1
		architectury: Architectury 4.0.30
		betterbiomeblend: Better Biome Blend 1.18.2-1.3.3-fabric
		betterf3: BetterF3 1.2.3
		blue_endless_jankson: jankson 1.2.1
		caffeineconfig: CaffeineConfig 1.0.0
		cardinal-components-base: Cardinal Components API (base) 4.1.4
		cardinal-components-entity: Cardinal Components API (entities) 4.1.4
		charm: Charm 4.0.0
		cloth-basic-math: cloth-basic-math 0.6.0
		cloth-config: Cloth Config v6 6.2.57
		clumps: Clumps 8.0.0+7
		com_electronwill_night-config_core: core 3.6.3
		com_electronwill_night-config_toml: toml 3.6.3
		com_eliotlash_mclib_mclib: mclib 18
		com_eliotlash_molang_molang: molang 18
		com_fasterxml_jackson_core_jackson-annotations: jackson-annotations 2.13.1
		com_fasterxml_jackson_core_jackson-core: jackson-core 2.13.1
		com_fasterxml_jackson_core_jackson-databind: jackson-databind 2.13.1
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		com_typesafe_config: config 1.4.1
		creeperoverhaul: Creeper Overhaul 1.3.0
		croptopia: Croptopia 1.8.1
		emerald_tools: Emerald Tools 1.3.38
		entityculling: EntityCulling-Fabric 1.5.0
		fabric: Fabric API 0.47.10+1.18.2
		fabric-api-base: Fabric API Base 0.4.3+d7c144a860
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.5.6+d7c144a860
		fabric-biome-api-v1: Fabric Biome API (v1) 8.0.2+801ec85b60
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.11+3ac43d9560
		fabric-command-api-v1: Fabric Command API (v1) 1.1.8+d7c144a860
		fabric-commands-v0: Fabric Commands (v0) 0.2.7+b4f4f6cd60
		fabric-containers-v0: Fabric Containers (v0) 0.1.20+d7c144a860
		fabric-content-registries-v0: Fabric Content Registries (v0) 3.0.1+d82b939260
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.10+3ac43d9560
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.16+2540745460
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.7+d7c144a860
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.18+d7c144a860
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.12+d7c144a860
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.12+d7c144a860
		fabric-item-api-v1: Fabric Item API (v1) 1.3.2+691a79b560
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.9+3ac43d9560
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.11+54e5b2ec60
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.9+b4f4f6cd60
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.0.1+2540745460
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.10+d7c144a860
		fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.0.3+d1027f7d60
		fabric-models-v0: Fabric Models (v0) 0.3.5+d7c144a860
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.20+d882b91560
		fabric-networking-v0: Fabric Networking (v0) 0.3.7+b4f4f6cd60
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 2.0.2+34b2a0ce60
		fabric-particles-v1: Fabric Particles (v1) 0.2.11+526dc1ac60
		fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.7+0d9ab37260
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.12+d882b91560
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.16+d8c7b9ae60
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.10+b4f4f6cd60
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.6+d7c144a860
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 2.0.1+54e5b2ec60
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.12+b4f4f6cd60
		fabric-rendering-v1: Fabric Rendering (v1) 1.10.6+54e5b2ec60
		fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.1+d1027f7d60
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.17+801ec85b60
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.9+d882b91560
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.13+d7c144a860
		fabric-textures-v0: Fabric Textures (v0) 1.0.11+3ac43d9560
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.5.13+cca23f9360
		fabricloader: Fabric Loader 0.13.3
		feature_nbt_deadlock_be_gone: Feature NBT Deadlock Be Gone - Fabric 2.0.0+1.18.2-rc1
		ferritecore: FerriteCore 4.2.0
		fishofthieves: Fish of Thieves 1.0.1
		forgeconfigapiport: Forge Config API Port 3.2.0
		geckolib3: Geckolib 3.0.35
		io_leangen_geantyref_geantyref: geantyref 1.3.11
		iris: Iris 1.2.1-rc2-0cc372f0-dirty
		jankson: Jankson 4.0.0+j1.2.0
		java: OpenJDK 64-Bit Server VM 17
		libgui: LibGui 5.1.0+1.18
		libninepatch: LibNinePatch 1.1.0
		lithium: Lithium 0.7.9
		mavm: More Axolotl Variants Mod 1.0.7a
		minecraft: Minecraft 1.18.2
		modmenu: Mod Menu 3.1.0
		myloot: myLoot 1.6
		omega-config: OmegaConfig 1.0.8
		org_anarres_jcpp: jcpp 1.4.14
		org_joml_joml: joml 1.10.2
		org_spongepowered_configurate-core: configurate-core 4.1.2
		org_spongepowered_configurate-hocon: configurate-hocon 4.1.2
		pugh_tools: Pugh Tools 1.2.0
		puzzleslib: Puzzles Lib 3.3.1
		repurposed_structures: Repurposed Structures 4.0.0+1.18.2
		seedfix: Seed Fix 1.0.1
		sodium: Sodium 0.4.1+build.15
		sodium-extra: Sodium Extra 0.4.1
		spark: spark 1.8.14
		spoornpacks: SpoornPacks 4.0-1.18.2
		tinyskeletons: Tiny Skeletons 3.2.0
		twigs: Twigs 1.1.3+legacy.1.18.2
		waystones: Waystones 2.5.0
		xaeroworldmap: Xaero's World Map 1.20.3.1
		yigd: You're in Grave Danger 1.3.1
	Launched Version: fabric-loader-0.13.3-1.18.2
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: Unknown
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: <unknown>

```

</details>

**Comment by spoorn** [comment]
My bad, I didn't update the library yet for 1.18.2

Please try updating SpoornPacks: https://www.curseforge.com/minecraft/mc-mods/spoornpacks

And while you're at it, update myLoot as well.

Reopen if issue persists

**Comment by PalePyth** [comment]
same error https://mclo.gs/DuMEqLa

**Comment by spoorn** [comment]
@PalePyth That's caused by owo-lib and mythic metals.  When you see an exception stacktrace like that, scan through it and usually towards the bottom is the real root cause
